# Structure

Shiny apps are contained in a single script called `app.R`. The structure can be broken into four parts:

- Shiny package. Load the shiny package in the script first. 

- User interface object. The user interface (ui) object controls the layout and appearance of your app.

- Server function. The server function contains the instructions that your computer needs to build your app

- `shinyApp` function. The shinyApp function creates Shiny app objects from an explicit UI/server pair.

The script `app.R` can be run like a typical R script or run like a app through a folder `runApp("newdir")`.

This is the way to run R shiny like a typical R object such as plots. 
```{r eval=FALSE}
# First part, load the package
library(shiny)

# Second part, define UI for the Shiny app
ui <- fluidPage(
  # App title ----
  titlePanel("Hello Shiny!"),
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    # Sidebar panel for inputs ----
    sidebarPanel(
      # Input: Slider for the number of bins ----
      sliderInput(inputId = "bins",
                  label = "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)
    ),
    # Main panel for displaying outputs ----
    mainPanel(
      # Output: Histogram ----
      plotOutput(outputId = "distPlot")
    )
  )
)

# Third part, define server logic required to draw a histogram
server <- function(input, output) {
  
  # Histogram of the Old Faithful Geyser Data ----
  # with requested number of bins
  # This expression that generates a histogram is wrapped in a call
  # to renderPlot to indicate that:
  #
  # 1. It is "reactive" and therefore should be automatically
  #    re-executed when inputs (input$bins) change
  # 2. Its output type is a plot
  output$distPlot <- renderPlot({
    x    <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "Waiting time to next eruption (in mins)",
         main = "Histogram of waiting times")
  })
}

# Fourth part, tie up ui and server
shinyApp(ui = ui, server = server)
```

The alternative way is to run the R shiny script remotely like a app. This can be achieved by creating a folder called *my_app* in your current working directory. Then save the R shiny script above into a R script file called `app.R` in the *my_app* folder. Then you can open a new R blank script and the R Shiny app should pop up when you run `runApp("my_app")` in the console. 
   


